/* Primarias
   Definición de claves primarias 
*/

ALTER TABLE USERS ADD CONSTRAINT  PK_USERS PRIMARY KEY(typeId, id);
ALTER TABLE DOCUMENTS ADD CONSTRAINT  PK_DOCUMENTS PRIMARY KEY(document_no,users_typeid,users_id);
ALTER TABLE QUALIFICATIONS ADD CONSTRAINT  PK_QUALIFICATIONS PRIMARY KEY(USERS_typeIdG, USERS_typeIdR, USERS_idG, USERS_idR);
ALTER TABLE HOSTERS ADD CONSTRAINT  PK_HOSTERS PRIMARY KEY(USERS_typeId, USERS_id);
ALTER TABLE COSTUMERS ADD CONSTRAINT  PK_COSTUMERS PRIMARY KEY(USERS_typeId, USERS_id);
ALTER TABLE EVENTS ADD CONSTRAINT  PK_EVENTS PRIMARY KEY(reference_code);
ALTER TABLE LEGAL_STANDARS ADD CONSTRAINT  PK_LEGAL_STANDARS PRIMARY KEY(legalStandar_no);
ALTER TABLE BARS ADD CONSTRAINT  PK_BARS PRIMARY KEY(nit);
ALTER TABLE TIMETABLES ADD CONSTRAINT  PK_TIMETABLES PRIMARY KEY(BARS_nit);
ALTER TABLE POSTS ADD CONSTRAINT  PK_POSTS PRIMARY KEY(post_no);
ALTER TABLE RESERVATIONS ADD CONSTRAINT  PK_RESERVATIONS PRIMARY KEY(reference_number);
ALTER TABLE PAYMENTS ADD CONSTRAINT  PK_PAYMENTS PRIMARY KEY(payment_no);
ALTER TABLE PRIORITIES ADD CONSTRAINT PK_PRIORITIES PRIMARY KEY(priorityPlan);
ALTER TABLE TICKETS ADD CONSTRAINT  PK_TICKETS PRIMARY KEY(order_number);
ALTER TABLE PLACES ADD CONSTRAINT  PK_PLACES PRIMARY KEY(place_no);
ALTER TABLE CUSTOMERS_BY_POSTS ADD CONSTRAINT  PK_CUSTOMERS_BY_POSTS PRIMARY KEY(COSTUMERS_USERS_typeId, COSTUMERS_USERS_id, POSTS_post_no);

/* Unicas
   Definición de claves únicas 
*/

ALTER TABLE TICKETS ADD CONSTRAINT UK_TICKETS_code_QR UNIQUE (code_QR);
ALTER TABLE USERS ADD CONSTRAINT UK_USERS_email UNIQUE (email);
ALTER TABLE USERS ADD CONSTRAINT UK_USERS_phone UNIQUE (phone);

/* Foraneas
   Definición de claves foraneas 
*/

ALTER TABLE TICKETS ADD CONSTRAINT FK_TICKETS_PAYMENTS  FOREIGN KEY(PAYMENTS_payment_no) REFERENCES PAYMENTS(payment_no) ON DELETE CASCADE;

ALTER TABLE PAYMENTS ADD CONSTRAINT FK_PAYMENTS_RESERVATIONS  FOREIGN KEY(RESERVATIONS_reference_number) REFERENCES RESERVATIONS(reference_number) ON DELETE CASCADE;
ALTER TABLE PAYMENTS ADD CONSTRAINT FK_PAYMENTS_POSTS  FOREIGN KEY(POSTS_post_no) REFERENCES POSTS(post_no) ON DELETE CASCADE;

ALTER TABLE RESERVATIONS ADD CONSTRAINT FK_RESERVATIONS_POSTS  FOREIGN KEY(POSTS_post_no) REFERENCES POSTS(post_no)ON DELETE CASCADE;

ALTER TABLE POSTS ADD CONSTRAINT FK_POSTS_EVENTS  FOREIGN KEY(EVENTS_reference_code) REFERENCES EVENTS(reference_code)ON DELETE CASCADE;
ALTER TABLE POSTS ADD CONSTRAINT FK_POSTS_PRIORITIES  FOREIGN KEY(PRIORITIES_priorityPlan) REFERENCES PRIORITIES(priorityPlan)ON DELETE CASCADE;

ALTER TABLE CUSTOMERS_BY_POSTS ADD CONSTRAINT FK_CAN_SEE_COSTUMERS FOREIGN KEY(COSTUMERS_USERS_typeId, COSTUMERS_USERS_id)REFERENCES COSTUMERS(USERS_typeId, USERS_id)ON DELETE CASCADE;
ALTER TABLE CUSTOMERS_BY_POSTS ADD CONSTRAINT FK_CUSTOMERS_BY_POSTS_POSTS  FOREIGN KEY(POSTS_post_no) REFERENCES POSTS(post_no)ON DELETE CASCADE;

ALTER TABLE COSTUMERS ADD CONSTRAINT FK_COSTUMERS_USERS  FOREIGN KEY(USERS_typeId, USERS_id) REFERENCES USERS(typeId, id)ON DELETE CASCADE;

ALTER TABLE DOCUMENTS ADD CONSTRAINT FK_DOCUMENTS_USERS  FOREIGN KEY(USERS_typeId, USERS_id) REFERENCES USERS(typeId, id) ON DELETE CASCADE;

ALTER TABLE QUALIFICATIONS ADD CONSTRAINT FK_QUALIFICATIONS_USERSG  FOREIGN KEY(USERS_typeIdG, USERS_idG) REFERENCES USERS(typeId, id)ON DELETE CASCADE;
ALTER TABLE QUALIFICATIONS ADD CONSTRAINT FK_QUALIFICATIONS_USERSR  FOREIGN KEY(USERS_typeIdR, USERS_idR) REFERENCES USERS(typeId, id)ON DELETE CASCADE;

ALTER TABLE HOSTERS ADD CONSTRAINT FK_HOSTERS_USERS  FOREIGN KEY(USERS_typeId, USERS_id) REFERENCES USERS(typeId, id)ON DELETE CASCADE;

ALTER TABLE BARS ADD CONSTRAINT FK_BARS_HOSTERS  FOREIGN KEY(HOSTERS_USERS_typeId, HOSTERS_USERS_id) REFERENCES HOSTERS(USERS_typeId, USERS_id)ON DELETE CASCADE;

ALTER TABLE TIMETABLES ADD CONSTRAINT FK_TIMETABLES_BARS  FOREIGN KEY(BARS_nit) REFERENCES BARS(nit)ON DELETE CASCADE;

ALTER TABLE EVENTS ADD CONSTRAINT FK_EVENTS_HOSTERS  FOREIGN KEY(HOSTERS_USERS_typeId, HOSTERS_USERS_id) REFERENCES HOSTERS(USERS_typeId, USERS_id)ON DELETE CASCADE;

ALTER TABLE LEGAL_STANDARS ADD CONSTRAINT FK_LEGAL_STANDARS_EVENTS  FOREIGN KEY(EVENTS_reference_code) REFERENCES EVENTS(reference_code) ON DELETE CASCADE;

ALTER TABLE PLACES ADD CONSTRAINT FK_PLACES_EVENTS  FOREIGN KEY(EVENTS_reference_code) REFERENCES EVENTS(reference_code) ON DELETE CASCADE;

