-- Eliminación de disparadores

alter trigger TR_COSTUMERS_BI DISABLE;
alter trigger TR_HOSTERS_BI DISABLE;
alter trigger TR_BARS_BI DISABLE;
alter trigger TR_BARS_AI DISABLE;
alter trigger TR_DOCUMENTS_BI DISABLE;

alter trigger TR_EVENTS_BI DISABLE;
alter trigger TR_POSTS_BI DISABLE;
alter trigger TR_RESERVATIONS_BI DISABLE;
alter trigger TR_LEGAL_STANDARS_BI DISABLE;
alter trigger TR_POSTS_BI2 DISABLE;
alter trigger TR_RESERVATIONS_BI2 DISABLE;
alter trigger TR_EVENTS_BU DISABLE;
alter trigger TR_POSTS_BU DISABLE;
alter trigger TR_RESERVATIONS_BU DISABLE;
alter trigger TR_PLACES_BU2 DISABLE;
alter trigger TR_PRIORITIES_BU DISABLE;
alter trigger TR_LEGAL_STANDARS_BU DISABLE;
alter trigger TR_CUSTOMERS_BY_POSTS_BU DISABLE;
alter trigger TR_PLACES_BU DISABLE;
alter trigger TR_EVENTS_BU2 DISABLE;
alter trigger TR_RESERVATIONS_BU2 DISABLE;
alter trigger TR_PLACES_BI DISABLE;
alter trigger TR_PLACES_BI2 DISABLE;
alter trigger TR_RESERVATIONS_BI3 DISABLE;
alter trigger TR_RESERVATIONS_BD DISABLE;
alter trigger TR_RESERVATIONS_BU4 DISABLE;

alter trigger TR_PAYMENTS_BI DISABLE;
alter trigger TR_TICKETS_BI DISABLE;
alter trigger TR_PAYMENTS_BI2 DISABLE;
alter trigger TR_PAYMENTS_BI3 DISABLE;
alter trigger TR_TICKETS_BI2 DISABLE;
alter trigger TR_PAYMENTS_BI4 DISABLE;
alter trigger TR_PAYMENTS_BU DISABLE;
alter trigger TR_PAYMENTS_AU DISABLE;
alter trigger TR_PAYMENTS_BU2 DISABLE;
alter trigger TR_PAYMENTS_BU3 DISABLE;
alter trigger TR_PAYMENTS_AU2 DISABLE;

DROP TRIGGER TR_COSTUMERS_BI;
DROP TRIGGER TR_HOSTERS_BI;
DROP TRIGGER TR_BARS_BI;
DROP TRIGGER TR_BARS_AI;
DROP TRIGGER TR_DOCUMENTS_BI;


DROP TRIGGER TR_EVENTS_BI;
DROP TRIGGER TR_POSTS_BI;
DROP TRIGGER TR_RESERVATIONS_BI;
DROP TRIGGER TR_LEGAL_STANDARS_BI;
DROP TRIGGER TR_POSTS_BI2;
DROP TRIGGER TR_RESERVATIONS_BI2;
DROP TRIGGER TR_EVENTS_BU;
DROP TRIGGER TR_POSTS_BU;
DROP TRIGGER TR_RESERVATIONS_BU;
DROP TRIGGER TR_PLACES_BU2;
DROP TRIGGER TR_PRIORITIES_BU;
DROP TRIGGER TR_LEGAL_STANDARS_BU;
DROP TRIGGER TR_CUSTOMERS_BY_POSTS_BU;
DROP TRIGGER TR_PLACES_BU;
DROP TRIGGER TR_EVENTS_BU2;
DROP TRIGGER TR_RESERVATIONS_BU2;
DROP TRIGGER TR_PLACES_BI;
DROP TRIGGER TR_PLACES_BI2;
DROP TRIGGER TR_RESERVATIONS_BI3;
DROP TRIGGER TR_RESERVATIONS_BD;
DROP TRIGGER TR_RESERVATIONS_BU4;

DROP TRIGGER TR_PAYMENTS_BI;
DROP TRIGGER TR_TICKETS_BI;
DROP TRIGGER TR_PAYMENTS_BI2;
DROP TRIGGER TR_PAYMENTS_BI3;
DROP TRIGGER TR_TICKETS_BI2;
DROP TRIGGER TR_PAYMENTS_BI4;
DROP TRIGGER TR_PAYMENTS_BU;
DROP TRIGGER TR_PAYMENTS_AU;
DROP TRIGGER TR_PAYMENTS_BU2;
DROP TRIGGER TR_PAYMENTS_BU3;
DROP TRIGGER TR_PAYMENTS_AU2;