/* Eliminación de datos */

DELETE FROM USERS;
DELETE FROM DOCUMENTS;
DELETE FROM QUALIFICATIONS;
DELETE FROM HOSTERS;
DELETE FROM COSTUMERS;
DELETE FROM EVENTS;
DELETE FROM LEGAL_STANDARS;
DELETE FROM BARS;
DELETE FROM TIMETABLES;
DELETE FROM POSTS;
DELETE FROM CUSTOMERS_BY_POSTS;
DELETE FROM PRIORITIES;
DELETE FROM RESERVATIONS;
DELETE FROM PAYMENTS;
DELETE FROM TICKETS;
DELETE FROM PLACES;
