/* Eliminación de tablas */

DROP TABLE USERS CASCADE CONSTRAINTS;
DROP TABLE DOCUMENTS CASCADE CONSTRAINTS;
DROP TABLE QUALIFICATIONS CASCADE CONSTRAINTS;
DROP TABLE HOSTERS CASCADE CONSTRAINTS;
DROP TABLE COSTUMERS CASCADE CONSTRAINTS;
DROP TABLE EVENTS CASCADE CONSTRAINTS;
DROP TABLE LEGAL_STANDARS CASCADE CONSTRAINTS;
DROP TABLE BARS CASCADE CONSTRAINTS;
DROP TABLE TIMETABLES CASCADE CONSTRAINTS;
DROP TABLE POSTS CASCADE CONSTRAINTS;
DROP TABLE CUSTOMERS_BY_POSTS CASCADE CONSTRAINTS;
DROP TABLE PRIORITIES CASCADE CONSTRAINTS;
DROP TABLE RESERVATIONS CASCADE CONSTRAINTS;
DROP TABLE PAYMENTS CASCADE CONSTRAINTS;
DROP TABLE TICKETS CASCADE CONSTRAINTS;
DROP TABLE PLACES CASCADE CONSTRAINTS;